### PR TITLE
Fixed #2 -  Improved html tag 'select' with multiple values.

### LINKED ISSUE #2: select - multiple
Hi @AnnaldasLalitkumar,

I love your code.

What is still missing for me is when **select** is selected multiple times.
So a dropdown with **multiple="multiple"**.

```html
<select id="1" name="1" multiple="multiple" >
  <option value="">-</option>
  <option value="1" selected="selected">1</option>
  <option value="2">2</option>
  <option value="3"selected="selected">3</option>
</select>
```
Can you get the selected values by length and return them comma separated?

```javascript
if (e(":selected", r).val().length > 1){}
```

best regards 
Denny

### PR DESCRIPTION
**Pull request by dennykorsukewitz**
Hi @AnnaldasLalitkumar 

I added a long (not minified) version of your code for better readability during further development.

Also changed the selection part to get comma separated values. 

```javascript
            if ("select" == a.toLowerCase()) {
                if (n.getValueByDesc ) {
                    if (r.val().length > 1) {
                        var text = e.trim(e(r).text());
                        var i = text.split("  ");
                        return i.join(",");
                    }else{
                        return e(":selected", r).text();
                    }
                }
                return r.val();
            }
            return "textarea" == a.toLowerCase() ? r.val() : t.text()
```

### CODE REVIEW

**Comment by dennykorsukewitz** [comment]
Hi @AnnaldasLalitkumar

How are you?
Are you still active?

Greetings,
Denny

**Comment by AnnaldasLalitkumar** [comment]
Hello @dennykorsukewitz 

I am doing good.. How about you?

I have gone through your contribution and would like to merge it into my main code.

Thank you for contributing.

**Comment by dennykorsukewitz** [comment]
Hi @AnnaldasLalitkumar 

Let's go then.

**Comment by AnnaldasLalitkumar** [comment]
Hi @dennykorsukewitz ,

I have checked for the above issue in the code but it seems that the plugin already supports selection of multiple options. Can you please help me out with your case in which you have faced this problem?

**Comment by dennykorsukewitz** [comment]
Hello @AnnaldasLalitkumar 

indeed. I can't find the missing code / error anymore either. 
But I can't track down and compare the forked code anymore either.
Apparently there was an overlap.

I know that my use case was even more specialised. 

Then I would say the problem is solved.

😄

**Pull request closed without merging**
